### ISSUE TITLE
add a podspec

### ISSUE THREAD

**Issue by haifengkao** [logentries/le_ios#10]
It would be nice to support cocoapods

An existing podspec can be found at 
https://github.com/sagmor/le_ios/commit/56dc81dbb91260c05395ca7362197defd429e16f

**Comment by elliotrock** [comment]
Please, very important for current workflows in iOS development

**Comment by vilda** [comment]
Just did, thanks @haifengkao! We'll need to find someone in our company to take responsibility for cocoapod and keep an eye on it.

**Comment by haifengkao** [comment]
thanks @vilda . If you like, I can take responsibility :)

**Comment by mackuba** [comment]
Was this actually submitted to the CocoaPods repo?
