### ISSUE TITLE
BSD license

### ISSUE THREAD

**Issue by mackuba** [logentries/le_ios#15]
Hi,

just to clarify, since you use the BSD license which says that reproductions in binary form must include the author's copyright info in the documentation - I'm assuming you don't actually require any such attribution in apps? (You might consider switching to MIT which only requires keeping the copyright info with the code.)

**Comment by vilda** [comment]
Nope, we don't require that. We'll change the license to MIT. Thanks for pointing this issue @mackuba

**Comment by vilda** [comment]
Done! Thanks again @mackuba

**Comment by mackuba** [comment]
Thanks!
