### ISSUE TITLE
Allow to turn off exception handler

### ISSUE THREAD

**Issue by vixentael** [logentries/le_ios#18]
Currently LogEntries handles crashes by default:

`lecore.m` file

```
int le_init()
{
    ...        
    NSSetUncaughtExceptionHandler(&le_exception_handler);
    ...
}
```

this is very inconvenient when you use another crash handler, like Crashlytics. Because it leads to kind of race -- only the one, who sets exception handler last, will handle crashes.

I suggest to **disable exception handling by default**, remove setting handler from init method and to add additional method for enabling, like this

```
void le_handle_crashes() {
    NSSetUncaughtExceptionHandler(&le_exception_handler);
}
```

OR **to add `define` macro** and check it in `le_init`

```
#define LE_HANDLE_CRASHES 1
```

then le_init could look like
```
int le_init()
{
    ...     
#if  LE_HANDLE_CRASHES
    NSSetUncaughtExceptionHandler(&le_exception_handler);
#endif
    ...
}
```

Logger initialization for those who use another crash reporting tool, will look like this:

```
#define LE_HANDLE_CRASHES 0
le_init();
le_set_token("..");
```

**Comment by vilda** [comment]
Thanks @vixentael, we'll discuss this internally and make the best option to make this feature adjustable. Alternatively, exception handling chain would improve things since even normal application may want to handle uncaught exceptions is some way.

**Comment by jedi4ever** [comment]
@vixentael @vilda +1 on this - when you use services like crashlytics etc... it makes sense to disable the crash handler from logentries

**Comment by hashier** [comment]
\:
I was realising that log entries was reporting crashes but I was just assuming that they would propagate it in the chain... Now I'm hoping I didn't miss any important crashes in Crashlytics.

@vixentael is it enough to remove the `NSSetUncaughtExceptionHandler` call in init?

**Comment by carlbac93** [comment]
@hashier is it enough to remove the NSSetUncaughtExceptionHandler call in init? Have you done anything else to disable it?

**Comment by jedi4ever** [comment]
https://github.com/smalltownheroes/le_ios/commit/bb892c3dcbdd7d22655c9ffc7ac24ae9fb4bd349

this is what we did in prod

**Comment by jedi4ever** [comment]
it makes me sad that logentries doesn't show much love for their oss components here on github

**Comment by hashier** [comment]
@carlbac93 @jedi4ever That's exactly the same what we did in prod

**Comment by hashier** [comment]
But it seems that le log is saving the old crash handler and after working on the exception it forwards it to the old one. It seemed to work fine for us together with Crashlytics. (Anyway, we disabled it now since no one checked for crashes on le log)

**Comment by vilda** [comment]
Sorry for the slow response here. We do chain exception handling, but I do understand that logging exceptions should be optional. I made #23 for this.
